proyecto_homepage:
    path:     /
    defaults: { _controller: ProyectoBundle:Default:index } 

proyecto_index:
    path:   /admin/index
    defaults: { _controller: ProyectoBundle:Admin:index }
    
proyecto_add:
    path:   /admin/add
    defaults: { _controller: ProyectoBundle:Admin:add } 
    
proyecto_edit:
    path:   /admin/edit/{id}
    defaults: { _controller: ProyectoBundle:Admin:edit, id: 1 } 

proyecto_view:
    path:   /admin/view{id}
    defaults: { _controller: ProyectoBundle:Admin:view } 

proyecto_contacto:
    path:   /admin/contacto
    defaults: { _controller: ProyectoBundle:Admin:contacto}

proyecto_usuarios:
    path:   /admin/usuarios
    defaults: { _controller: ProyectoBundle:Admin:usuarios}

proyecto_auto:
    path:   /admin/auto
    defaults: { _controller: ProyectoBundle:Admin:auto}

    
proyecto_lugares:
    path:   /admin/lugares
    defaults: { _controller: ProyectoBundle:Admin:lugares}



proyecto_about:
    path:   /admin/about
    defaults: { _controller: ProyectoBundle:Admin:about} 
    


#-----------Redes login-------------


#------------------------------------------------------
  
lugar_index:
    path:   /lugar/index/{id}
    defaults: { _controller: ProyectoBundle:Lugar:index }
    
lugar_new:
    path:   /lugar/new/{establecimiento}
    defaults: { _controller: ProyectoBundle:Lugar:new }

lugar_delete:
    path:   /lugar/delete/{id}/{establecimiento}
    defaults: { _controller: ProyectoBundle:Lugar:delete }   

lugar_buscar:
    path:   /lugar/buscar/{establecimiento}/{check_value}
    defaults: { _controller: ProyectoBundle:Lugar:buscar }

#--------------para usuario-----------------------------------
usuario_index:
    path:     /usuario/index
    defaults: { _controller: ProyectoBundle:Usuario:index }
usuario_new:
    path:     /new
    defaults: { _controller: ProyectoBundle:Usuario:new }
usuario_edit:
    path:     /usuario/edit
    defaults: { _controller: ProyectoBundle:Usuario:edit }

usuario:
    path: /cuenta
    defaults: {_controller: ProyectoBundle:Usuario:cuenta}
#-----------------para la autenticacion---------------------
app_usuario:
    resource: "@ProyectoBundle/Controller/UsuarioController.php"
    type:     annotation

#para la autenticacion
login:
    path:     /login
    defaults: { _controller: ProyectoBundle:Security:login }

logout:
    path:   /logout
#    defaults: { _controller: ProyectoBundle:Security:login} 

#login_check:
#    path: /login_check
#logout:
#    path: /logout

establecimientos:
    path: /establecimientos/{localidad}
    defaults: { _controller: ProyectoBundle:Establecimiento:index, localidad:todas}

establecimiento_puntual:
    path: /establecimiento/{id}
    defaults: { _controller: ProyectoBundle:Establecimiento:puntual}

reservar:
    path: /reservar/{lugar}/{desde}/{hasta}/{auto}
    defaults: { _controller: ProyectoBundle:Establecimiento:reservar}

maps:
    path: /maps
    defaults: { _controller: ProyectoBundle:Establecimiento:maps}
auto_new:
    path:     auto/new
    defaults: { _controller: ProyectoBundle:Auto:new }

buscar_lugares_est:
    path: /establecimientos/buscar/{establecimiento}/{fechaDesde}/{fechaHasta}
    defaults: { _controller: ProyectoBundle:Lugar:buscarXHorario }