proyecto_homepage:
    path:     /
    defaults: { _controller: ProyectoBundle:Default:index } 

proyecto_index:
    path:   /admin/index
    defaults: { _controller: ProyectoBundle:Admin:index }
    
proyecto_add:
    path:   /admin/add
    defaults: { _controller: ProyectoBundle:Admin:add } 
    
proyecto_edit:
    path:   /admin/edit/{id}
    defaults: { _controller: ProyectoBundle:Admin:edit, id: 1 } 

proyecto_view:
    path:   /admin/view{id}
    defaults: { _controller: ProyectoBundle:Admin:view } 

proyecto_contacto:
    path:   /admin/contacto
    defaults: { _controller: ProyectoBundle:Admin:contacto} 
    
 #NO SIVE, SENDMAIL, SE DEJA PARA EJEMPLO.
proyecto_sendmail:
    path:   /admin/sendmail
    defaults: { _controller: ProyectoBundle:Admin:sendmail} 

  
  
lugar_index:
    path:   /lugar/index
    defaults: { _controller: ProyectoBundle:Lugar:index }
    
lugar_new:
    path:   /Lugar/new
    defaults: { _controller: ProyectoBundle:Lugar:new }   


proyecto_usuario:
    resource: "@ProyectoBundle/Controller/UsuarioController.php"
    type:     annotation
app_usuario:
    resource: "@ProyectoBundle/Controller/UsuarioController.php"
    type:     annotation
usuario_login:
    path:   /usuario/login
    defaults: { _controller: ProyectoBundle:Usuario:login} 
