proyecto_homepage:
    path:     /
    defaults: { _controller: ProyectoBundle:Default:index } 

proyecto_index:
    path:   /admin/index
    defaults: { _controller: ProyectoBundle:Admin:index }
    
proyecto_add:
    path:   /admin/add
    defaults: { _controller: ProyectoBundle:Admin:add } 
    
proyecto_edit:
    path:   /admin/edit/{id}
    defaults: { _controller: ProyectoBundle:Admin:edit, id: 1 } 

proyecto_view:
    path:   /admin/view{id}
    defaults: { _controller: ProyectoBundle:Admin:view } 

proyecto_contacto:
    path:   /admin/contacto
    defaults: { _controller: ProyectoBundle:Admin:contacto} 
    
proyecto_about:
    path:   /admin/about
    defaults: { _controller: ProyectoBundle:Admin:about} 
    
 #NO SIVE, SENDMAIL, SE DEJA PARA EJEMPLO.
proyecto_sendmail:
    path:   /admin/sendmail
    defaults: { _controller: ProyectoBundle:Admin:sendmail} 

  
  
lugar_index:
    path:   /lugar/index
    defaults: { _controller: ProyectoBundle:Lugar:index }
    
lugar_new:
    path:   /Lugar/new
    defaults: { _controller: ProyectoBundle:Lugar:new }   

#--------------para usuario-----------------------------------
usuario_index:
    path:     /usuario/index
    defaults: { _controller: ProyectoBundle:Usuario:index }
usuario_new:
    path:     /usuario/new
    defaults: { _controller: ProyectoBundle:Usuario:new }
#-----------------para la autenticacion---------------------
app_usuario:
    resource: "@ProyectoBundle/Controller/UsuarioController.php"
    type:     annotation

#para la autenticacion
usuario_login:
    path:     /login
    defaults: { _controller: ProyectoBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: ProyectoBundle:Security:loginCheck }

logout:
    path:     /logout
#    defaults: { _controller: ProyectoBundle:Security:login} 

#login_check:
#    path: /login_check
#logout:
#    path: /logout

establecimientos:
    path: /establecimientos/{localidad}
    defaults: { _controller: ProyectoBundle:Establecimiento:index, localidad:todas}

