proyecto_homepage:
    path:     /
    defaults: { _controller: ProyectoBundle:Default:index } 

proyecto_index:
    path:   /admin/index
    defaults: { _controller: ProyectoBundle:Admin:index }
    
proyecto_add:
    path:   /admin/add
    defaults: { _controller: ProyectoBundle:Admin:add } 
    
proyecto_edit:
    path:   /admin/edit/{id}
    defaults: { _controller: ProyectoBundle:Admin:edit, id: 1 } 

proyecto_view:
    path:   /admin/view{id}
    defaults: { _controller: ProyectoBundle:Admin:view } 

proyecto_contacto:
    path:   /admin/contacto
    defaults: { _controller: ProyectoBundle:Admin:contacto} 
    
proyecto_contacto2:
    path:   /admin/contacto2
    defaults: { _controller: ProyectoBundle:Admin:contacto2} 
    
#proyecto_delete:
 #   path:   /user/delete{id}
  #  defaults: { _controller: ProyectoBundle:User:delete }
  
  
lugar_index:
    path:   /Lugar/index
    defaults: { _controller: ProyectoBundle:Lugar:index }  