proyecto_homepage:
    path:     /
    defaults: { _controller: ProyectoBundle:Default:index } 

proyecto_index:
    path:   /admin/index
    defaults: { _controller: ProyectoBundle:Admin:index }
    
proyecto_add:
    path:   /admin/add
    defaults: { _controller: ProyectoBundle:Admin:add } 
    
proyecto_edit:
    path:   /admin/edit/{id}
    defaults: { _controller: ProyectoBundle:Admin:edit, id: 1 } 

proyecto_view:
    path:   /admin/view{id}
    defaults: { _controller: ProyectoBundle:Admin:view } 

proyecto_contacto:
    path:   /admin/contacto
    defaults: { _controller: ProyectoBundle:Admin:contacto} 
    
proyecto_about:
    path:   /admin/about
    defaults: { _controller: ProyectoBundle:Admin:about} 
    
 #NO SIVE, SENDMAIL, SE DEJA PARA EJEMPLO.
proyecto_sendmail:
    path:   /admin/sendmail
    defaults: { _controller: ProyectoBundle:Admin:sendmail}

#-----------Redes login-------------


#------------------------------------------------------
  
lugar_index:
    path:   /lugar/index/{id}
    defaults: { _controller: ProyectoBundle:Lugar:index }
    
lugar_new:
    path:   /lugar/new/{establecimiento}
    defaults: { _controller: ProyectoBundle:Lugar:new }   

#--------------para usuario-----------------------------------
usuario_index:
    path:     /usuario/index
    defaults: { _controller: ProyectoBundle:Usuario:index }
usuario_new:
    path:     /new
    defaults: { _controller: ProyectoBundle:Usuario:new }

usuario:
    path: /cuenta
    defaults: {_controller: ProyectoBundle:Usuario:cuenta}
#-----------------para la autenticacion---------------------
app_usuario:
    resource: "@ProyectoBundle/Controller/UsuarioController.php"
    type:     annotation

#para la autenticacion
login:
    path:     /login
    defaults: { _controller: ProyectoBundle:Security:login }

logout:
    path:   /logout
#    defaults: { _controller: ProyectoBundle:Security:login} 

#login_check:
#    path: /login_check
#logout:
#    path: /logout

establecimientos:
    path: /establecimientos/{localidad}
    defaults: { _controller: ProyectoBundle:Establecimiento:index, localidad:todas}

establecimiento_puntual:
    path: /establecimiento/{id}
    defaults: { _controller: ProyectoBundle:Establecimiento:puntual}

reservar:
    path: /reservar/{id}
    defaults: { _controller: ProyectoBundle:Establecimiento:reservar}

maps:
    path: /maps
    defaults: { _controller: ProyectoBundle:Establecimiento:maps}
auto_new:
    path:     auto/new
    defaults: { _controller: ProyectoBundle:Auto:new }