proyecto_homepage:
    path:     /
    defaults: { _controller: ProyectoBundle:Default:index } 

proyecto_index:
    path:   /user/index
    defaults: { _controller: ProyectoBundle:User:index }
    
proyecto_add:
    path:   /user/add
    defaults: { _controller: ProyectoBundle:User:add } 
    
proyecto_edit:
    path:   /user/edit/{id}
    defaults: { _controller: ProyectoBundle:User:edit, id: 1 } 

proyecto_view:
    path:   /user/view{id}
    defaults: { _controller: ProyectoBundle:User:view } 
    
proyecto_delete:
    path:   /user/delete{id}
    defaults: { _controller: ProyectoBundle:User:delete } 