<?php

namespace ProyectoBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
/**
 * autoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class autoRepository extends EntityRepository 
{

}
