<?php

namespace ProyectoBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
/**
 * usuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuarioRepository extends EntityRepository implements UserLoaderInterface
{
     public function loadUserByUsername($username)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.e_mail = :e_mail')
            ->setParameter('username', $username)
            ->setParameter('e_mail', $e_mail)
            ->getQuery()
            ->getOneOrNullResult();
        
        if (null === $user) {
            $message = sprintf(
                'Unable to find an active admin AppBundle:User object identified by "%s".',
                $username
            );
            throw new UsernameNotFoundException($message);
        }
        return $user;
    }
}
