# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: ProyectoBundle:Usuario
               
        in_memory:
            memory: 
                users:
                    user:
                        password: notnull
                        roles: 'ROLE_USER'
                    admin:
                        password: notnull
                        roles: 'ROLE_ADMIN'
    firewalls:
        default:
            anonymous: ~
            http_basic: ~

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
#            providers: our_db_provider
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
#            
            provider: our_db_provider
            form_login:
              login_path: /login
              check_path: /login_check
              
              default_target_path: default_security_target 
              use_referer: true
              failure_path: login_failure
              target_path_parameter: redirect_url

            logout:
              path: logout
              target: /
             
    encoders:
          Symfony\Component\Security\Core\User\User: plaintext
          ProyectoBundle\Entity\Usuario: bcrypt
          
