
security:

    
    providers:
        database:
            entity:
                 class: ProyectoBundle:Usuario
                 property: usuario
        in_memory:
            memory: 
                users:
                    ryan:
                        password: 1234
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    
                
    encoders:

        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt
            cost: 12
        ProyectoBundle\Entity\Usuario:
            algorithm: bcrypt 
        
        
              
          
            
                          
    firewalls:
        main:
            anonymous: ~ 
            http_basic: ~
            provider: database
            form_login: 
                login_path: login
                check_path: login  
            logout:
                path: logout
                target: /


        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
         
           
    
       # main:
      #      anonymous: ~
#            providers: our_db_provider
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
#            
     
            
 
    
      
    access_control: 
        
         # require ROLE_ADMIN for /admin*
         - { path: ^/admin, role: ROLE_USER }
         - { path: ^/Default, role: ROLE_USER }




    