# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
                entity:
                    class: ProyectoBundle:Usuario
                    property: username
               
        in_memory:
            memory: 
                users:
                    ryan:
                        password: $2a$12$uD3L84LOkDL1WR5UEdEQBedbPFdkADKuC6yTjU8O4uBJRctFdrCU.
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$12$uD3L84LOkDL1WR5UEdEQBedbPFdkADKuC6yTjU8O4uBJRctFdrCU.
                        roles: 'ROLE_ADMIN'
    firewalls:
        default:
            anonymous: ~
            http_basic: ~

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

       # main:
      #      anonymous: ~
#            providers: our_db_provider
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
#            
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login 
            logout:
                path: /logout
                target: /
             
    encoders:
          ProyectoBundle\Entity\Usuario: bcrypt
          
          
    access_control : 
        - { path: ^/login$, allow_if: 'is_anonymous()' }
        - { path: ^/usuario/new, allow_if: 'is_anonymous()' }
        - { path: ^/admin, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER