<?php

namespace AppBundle\Repository;

/**
 * lucasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lucasRepository extends \Doctrine\ORM\EntityRepository
{
}
